import { ContractProvider } from "@/app/components/provider/ContractProvider";
import { UserProvider } from "@/app/components/provider/UserProvider";
import { Children } from "@/app/lib/types";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Children) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <ContractProvider>{children}</ContractProvider>
        </UserProvider>
      </body>
    </html>
  );
}
